package com.recruitcrm.web;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.UUID;

/**
 * Stores uploaded resume PDFs on disk.
 *
 * The browser sends the file as a Base64 string inside an ordinary form
 * field, so the existing form parser handles it and no multipart parser
 * is needed. Simpler, and it keeps the project free of extra libraries.
 *
 * Supporting plumbing, NOT a design pattern.
 */
public final class ResumeStorage {

    /** Roughly 2 MB of actual PDF. */
    private static final int MAX_BYTES = 2 * 1024 * 1024;
    private static final String RESUME_DIR = "data/resumes";

    private ResumeStorage() {}

    /**
     * Decodes, validates and saves a Base64-encoded PDF.
     *
     * @return the public URL path, e.g. "/api/resumes/ab12cd34.pdf"
     * @throws IllegalArgumentException if missing, too large, or not a PDF
     */
    public static String saveBase64Pdf(String base64Data) {
        if (base64Data == null || base64Data.isBlank()) {
            throw new IllegalArgumentException("No file data received");
        }

        // Browsers send "data:application/pdf;base64,JVBERi0x..." - strip the prefix.
        String payload = base64Data;
        int comma = payload.indexOf(',');
        if (payload.startsWith("data:") && comma > -1) {
            payload = payload.substring(comma + 1);
        }

        byte[] bytes;
        try {
            bytes = Base64.getDecoder().decode(payload);
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Uploaded file could not be read");
        }

        if (bytes.length == 0) {
            throw new IllegalArgumentException("Uploaded file is empty");
        }
        if (bytes.length > MAX_BYTES) {
            throw new IllegalArgumentException("Resume must be smaller than 2 MB");
        }
        if (!looksLikePdf(bytes)) {
            throw new IllegalArgumentException("Only PDF files are accepted");
        }

        // The filename is generated by us, never taken from the upload. A
        // user-supplied name could contain "../" and write outside this folder.
        String filename = UUID.randomUUID().toString().substring(0, 8) + ".pdf";

        try {
            File dir = new File(RESUME_DIR);
            dir.mkdirs();
            Files.write(new File(dir, filename).toPath(), bytes);
        } catch (IOException e) {
            throw new IllegalStateException("Could not save the uploaded resume", e);
        }

        return "/api/resumes/" + filename;
    }

    /** Reads a stored resume back. Returns null if it does not exist. */
    public static byte[] read(String filename) {
        if (!isSafeFilename(filename)) {
            return null;
        }
        Path path = new File(RESUME_DIR, filename).toPath();
        if (!Files.exists(path)) {
            return null;
        }
        try {
            return Files.readAllBytes(path);
        } catch (IOException e) {
            return null;
        }
    }

    /**
     * Every real PDF begins with the bytes "%PDF". Checking this stops
     * someone renaming an executable to .pdf - the browser's accept
     * attribute is only a hint and is trivial to bypass.
     */
    private static boolean looksLikePdf(byte[] bytes) {
        return bytes.length > 4
                && bytes[0] == '%' && bytes[1] == 'P' && bytes[2] == 'D' && bytes[3] == 'F';
    }

    /** Guards the download route against path traversal such as "../../secrets". */
    private static boolean isSafeFilename(String filename) {
        return filename != null && filename.matches("[a-zA-Z0-9]+\\.pdf");
    }
}
